### ISSUE TITLE
[Help]: Setting userdata

### ISSUE THREAD

**Issue by swbsf** [outscale/docker-machine-driver-outscale#35]
### Description

Hi!

Using rancher, thanks to the driver, we can set many things on our node template but not the cloud-init configuration. I was just wondering how do you get your node to join cluster if you are not relying on user-data?

Thanks.

**Comment by outscale-mdr** [comment]
Hello @swbsf,

Thank you for reaching out.

Rancher uses agent to deploy clusters and then the agents are responsible to deloy containers and to join the cluster.

For rke1, the cluster should create without any problem but for rke2 we have done some changes to be able to install the CCM (see [here](https://github.com/outscale-dev/osc-k8s-rancher) for a cluster template).

Best regards,
Maxime

**Comment by swbsf** [comment]
Ok thanks for the quick answer, we managed to deploy everything using helm.
